### PR TITLE
dataset: remove unused interface

### PR DESCRIPTION
**Pull request by yorkie**
I searched the datacook and pipcook projects, and removed it because of useless.

### CODE REVIEW

**Comment by FeelyChau** [comment]
It's useful interface for dataset. As a dataset, we could define the meta without labelMap as follow:
```js
{
   type: DatasetType.Image;
   size: {
     train: 100,
     test: 20
  }
}
```

**Comment by yorkie** [comment]
Ok, what's the purpose to define a dataset without labelMap?

**Comment by FeelyChau** [comment]
See: https://github.com/FeelyChau/Pipcook-Addition-RNN/blob/js/src/datasource.js#L72
In this case, labelMap is not necessary, the label and data are all strings.

**Comment by yorkie** [comment]
> See: https://github.com/FeelyChau/Pipcook-Addition-RNN/blob/js/src/datasource.js#L72
> In this case, labelMap is not necessary, the label and data are all strings.

It's conflicting with [the type declaration](https://github.com/imgcook/datacook/blob/bff1970a67eb4f5609a60bf5c17989cca7acf009/src/dataset/utils.ts#L91), should `datasetMeta` be extended from `BaseDatasetMeta`?

**Comment by FeelyChau** [comment]
> > See: https://github.com/FeelyChau/Pipcook-Addition-RNN/blob/js/src/datasource.js#L72
> > In this case, labelMap is not necessary, the label and data are all strings.
> 
> It's conflicting with [the type declaration](https://github.com/imgcook/datacook/blob/bff1970a67eb4f5609a60bf5c17989cca7acf009/src/dataset/utils.ts#L91), should `datasetMeta` be extended from `BaseDatasetMeta`?

I think we should change the `extends` condition to `BaseDatasetMeta`.

**Comment by yorkie** [comment]
Fixed :)

**Review by FeelyChau — APPROVED** [review]
LGTM.

**Review by WenheLI — APPROVED** [review]
LGTM

**Pull request merged**
