### PR TITLE
doc: add sections in readme

### PR DESCRIPTION
**Pull request by yorkie**
This renames the package name to @pipcook/datacook, adds examples.

### CODE REVIEW

**Comment by yorkie** [comment]
@risenW @steveoni I have created a team @imgcook/data-scientist and invited you, feel free to join us in this way :)

**Review by risenW — APPROVED** [review]

**Comment by yorkie** [comment]
Ping @WenheLI @steveoni :)

**Review by steveoni — APPROVED** [review]
@yorkie  LGTM

**Review by WenheLI — APPROVED** [review]
LGTM

**Pull request merged**
